### ISSUE TITLE
l1ttl35n1pp3r Fails on ssh -p 3030 root@10.10.10.1

### ISSUE THREAD

**Issue by q-33** [CyborgUnplug/CyborgUnplug#1]
Hello:

Both 1337 and non-1337 versions of password attempted. Nothing seems to work on this US keyboard. Have you changed it since posting the README? Copy/paste from README (without the spaces) and the results are posted below.

Excellent work on this. It will (hopefully) keep some of my crew protected at Burning Man this year.

Cheers,
Ken

[digit@digit CyborgUnplug]$ ssh -p 3030 root@10.10.10.1
            __                                  __  
  ______ **/ /  ___  _____** _  __ _____  ___  / /_ _____ _
 / **/ // / _ \/ _ \/ __/ _ `/ / // / _ \/ _ \/ / // / _`/
 \**/_, /_.__/_**/_/  \_, /  _,_/_//_/ .**/_/\_,_/\_, / 
    /**_/              /**_/           /_/          /___/ 

---

 Built on OpenWrt BARRIER BREAKER (Bleeding Edge) r41679

---

 http://plugunplug.net
 http://openwrt.org

---

root@10.10.10.1's password: 
Permission denied, please try again.
root@10.10.10.1's password:

**Comment by JulianOliver** [comment]
..on Wed, Jul 29, 2015 at 02:31:08PM -0700, q-33 wrote:

> Hello:
> 
> Both 1337 and non-1337 versions of password attempted. Nothing seems to work on this US keyboard. Have you changed it since posting the README? Copy/paste from README (without the spaces) and the results are posted below.

Hmm, odd. Perhaps the /etc/shadow file was changed. Thanks for the pointer, will
look into this tonight or tomorrow and let you know.

> Excellent work on this. It will (hopefully) keep some of my crew protected at Burning Man this year.

Thanks for the kind words! I'll commit some new source and fw within a week. It
has some new features like VPN support: tunnel any device associated with the
unplug through a OpenVPN server of your choice ;)

Cheers,

## 

Julian Oliver
http://julianoliver.com
http://criticalengineering.org
PGP key: https://julianoliver.com/key.asc
Beware the auto-complete life.

**Comment by q-33** [comment]
> Hmm, odd. Perhaps the /etc/shadow file was changed. Thanks for the pointer, will look into this tonight or tomorrow and let you know.

I'm in the process of rebuilding with an altered shadow file. However, not sure if there's a way to flash without being root. =/ For what it's worth, the password works fine for connecting the initial wireless network -- Just not for root access over ssh.

Performed the battery mod today to run on my scooter. This way we can drive it directly to The Man when we rig pyrotechnics. No joke, this might save a life. We are experiencing drone issues when rigging pyrotechnics and this just might solve that problem. Big ass kudos to you.

Cheers.

**Comment by melucas** [comment]
Did you ever sort out what the root password is for ssh access?

**Comment by nconder** [comment]
I could not get root access either.

**Comment by JulianOliver** [comment]
..on Wed, Oct 14, 2015 at 03:37:26PM -0700, Michael Lucas wrote:

> Did you ever sort out what the root password is for ssh access?

Did you try telnet 10.10.10.1 first?

If you did and it ssh still doesn't work after that then something is indeed
wrong and I'll fix it and push a new firmware. 

j

## 

Julian Oliver
http://julianoliver.com
http://criticalengineering.org
PGP key: https://julianoliver.com/key.asc
Beware the auto-complete life.

**Comment by nconder** [comment]
Here is my session using root password l1ttl35n1pp3r = Lima,1,Tango,Tango,Lima,3,5,November,1,Papa,Papa,3,Romeo

I tried ssh over WiFi and Ethernet.

Any ideas on recovery?

Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[10.10.10.1]:3030' (RSA) to the list of known hosts.
            __                                  __  
  ______ **/ /  ___  _____** _  __ _____  ___  / /_ _____ _
 / **/ // / _ \/ _ \/ __/ _ `/ / // / _ \/ _ \/ / // / _`/
 \**/_, /_.__/_**/_/  \_, /  _,_/_//_/ .**/_/\_,_/\_, / 
    /**_/              /**_/           /_/          /___/ 

---

 Built on OpenWrt BARRIER BREAKER (Bleeding Edge) r41679

---

 http://plugunplug.net
 http://openwrt.org

---

root@10.10.10.1's password: 
Permission denied, please try again.
root@10.10.10.1's password: 
Permission denied, please try again.
root@10.10.10.1's password: 
Permission denied (publickey,password).

**Comment by JulianOliver** [comment]
Can you try  'unplug' as pw? 

TBH I need to bring that branch up in line with Master, which has a heap of new goodness. Apologies for the delay, just want to harden Master a little more and then I'll look after this target.

**Comment by nconder** [comment]
The password unplug would not work either.

**Comment by JulianOliver** [comment]
OK, new image coming tomorrow.

**Comment by nconder** [comment]
THX.
Slight turn... did some features have to be removed in this upcoming release due to regulations from the "internationally influential regulatory body"? Or are those features not part of the open source release?
Regardless thanks for your work on this cant wait for my Little Snipper to get in!

**Comment by JulianOliver** [comment]
A good question: all the features will be available on the 'Homebake' release. It's open source so the Seller vs Regulator doesn't apply here.

**Comment by JulianOliver** [comment]
@nconder  Thanks for your patience, by the way. Months and months of lawyers to get this far...

**Comment by JulianOliver** [comment]
Hi, please try the new firmware I just pushed. It should have the correct /etc/shadow file now..

**Comment by nconder** [comment]
Because I do not have root access to the I would have to follow the un-brick procedures first to update the firmware correct?

**Comment by JulianOliver** [comment]
Unfortunately, yes. 

Do you have serial interface to it? Pretty essential anyway, during experimentation.

**Comment by nconder** [comment]
"All your base are belong to us" root access works with the newly uploaded image!

**Comment by JulianOliver** [comment]
;-)
