### ISSUE TITLE
Rename / Identify Main User Sections

### ISSUE THREAD

**Issue by bnvk** [CyborgUnplug/CyborgUnplug#11]
There are many different ways to configure and use CyborgUnplug, and as we discussed (back in Dec) renaming the main "overview" items of this makes sense to be more user friendly

## detect

- Detect 
- Protect
- Little Snipper

## encrypt

- Protected Internet
- Protected Browsing
- Secure Internet

## share

- Local Sharing
- File Sharing
- Share Files
- Share Locally

## bridge

- Wifi Bridge
- Connect to Wifi

**Comment by JulianOliver** [comment]
See https://github.com/CyborgUnplug/CyborgUnplug/issues/14#issuecomment-291906367 and tell me what you think so far.

**Comment by bnvk** [comment]
I think we're pretty settled on:

- Detect spy devices
- Connect to VPN
- Create a Wifi Bridge
- Share files over Wifi

So closing this now!
