### ISSUE TITLE
Updates to "encrypt" section

### ISSUE THREAD

**Issue by bnvk** [CyborgUnplug/CyborgUnplug#14]
The following are items I came across on my first pass in the section currently known as **encrypted** (name subject to change).

- [x] Change name "Encrypt" to "Protect Traffic"
- [x] Add country flag icons
- [x] Parse and extract VPN info upon "adding" it
- [x] Save an "added" VPN configuration file
- [x] Error reporting on why an added VPN fails
- [x] Add auto-connect to VPN on startup

**Comment by JulianOliver** [comment]
Great ideas. I can take care of 3/4/5/6.

**Comment by JulianOliver** [comment]
Just an update that 3/4/6 have been taken care of in previous commits. Will commit 1 and look into 5 next.

**Comment by JulianOliver** [comment]
Ok took the liberty to make a few other buttons in the main menu more descriptive as actions. Commit https://github.com/CyborgUnplug/CyborgUnplug/commit/3c4d96d38f8d1a316703a643c6116a4aa1a44765

Screenshot on a Moto G:

![screenshot_20170405-173902](https://cloud.githubusercontent.com/assets/153270/24714190/18abc7b2-1a28-11e7-8135-604e5a7ecc0e.png)

**Comment by JulianOliver** [comment]
Looking into 5, I'm not sure it's possible without building a database of every possible OpenVPN failure condition and best-guess grepping against OpenVPN log output (not to mention quirky or even customised responses from whichever server the plug is being told to connect to). 

Thankfully, however, OpenVPN log output as regards errors of any sort are generally human readable and helpful, so I've committed https://github.com/CyborgUnplug/CyborgUnplug/commit/d64e6dc819e6113c75e8cb550ef11dc92c794e1a instead - log output in the VPN interface which will plainly report most common issues (auth/key/cert/timeout failures). This is a good solution, I think.

**Comment by bnvk** [comment]
Flags was added in 97a6f151db681bf57d8243345b6597b9fb82bdb4 so closing now!
