### ISSUE TITLE
Add custom hostname (even if only .local) to device

### ISSUE THREAD

**Issue by bnvk** [CyborgUnplug/CyborgUnplug#17]
Instead of a user having to go to `http://10.10.11.1` in their browser, being able to go to one of the following

```
http://unplug
http://unplug.local
```

Either of which would be superior to the IP address which is technical and thus likely prone to user error. If neither of these are possible #16 will be a nice stop gap.

**Comment by JulianOliver** [comment]
Definitely a better direction. In fact while less memorable, currently _http://littlesnipper.local_ works using Avahi, derived directly from $HOSTNAME. 

We need to resolve whether _http://unplug.local_ will be sane however when we release another hardware iteration (for instance the fabled 'Axe').

**Comment by JulianOliver** [comment]
OK, let's go with _snip.local_. Gets around the issue of so many misspelling 'snipper' as 'sniper'. Committed https://github.com/CyborgUnplug/CyborgUnplug/commit/68ee6c5e0e964eae01b2290c9e5903a9f7cb9663 and now closing this issue.
