### ISSUE TITLE
Allow "bridge mode" to save passwords for access points

### ISSUE THREAD

**Issue by bnvk** [CyborgUnplug/CyborgUnplug#18]
Upon connecting to an access point, the bridge tool MUST provide the ability to save the access point password and SHOULD do this as an automatic default which is selected.

**Comment by JulianOliver** [comment]
I agree this is important. Only procrastinating issue on my part is that if the plug is stolen and/or an attacker has temporary physical access and knows the root password, these keys can be removed from the device. This in fact is why I didn't implement it in the first instance. Naturally no option for an encrypted FS given this is SPI flash on a keyboardless / screenless embedded device!

Perhaps this should simply be something we can warn people about in the UI.

**Comment by JulianOliver** [comment]
Done. Waiting for a UI massage from you however! https://github.com/CyborgUnplug/CyborgUnplug/commit/576994d644926e73054cd05c08c5122e87c5c714
