### ISSUE TITLE
Allow for "bridge mode" to auto reconnect to an access points

### ISSUE THREAD

**Issue by bnvk** [CyborgUnplug/CyborgUnplug#19]
When using bridge mode and ones device restarts (or boots up) a user must go through all steps to connect to that access point. While this is good from a security / privacy point-of-view (knowing what your device is doing and recording), it is bad from a usability perspective.

This requires #18 to be completed and MUST offer users "optional" use of this feature and SHOULD default to `off`

**Comment by JulianOliver** [comment]
Oops, forgot to mention I implemented this a few commits back. Closing now.
