### ISSUE TITLE
Selecting Report Only mode goes to All Out mode page

### ISSUE THREAD

**Issue by nconder** [CyborgUnplug/CyborgUnplug#2]
Selecting the "Report Only" Mode will take you to the "All Out Mode" warning page. But according to the /www/config/mode file it is reporting as "alarm" and not allout.

**Comment by JulianOliver** [comment]
Onto this tomorrow, thanks for the pointer

**Comment by JulianOliver** [comment]
This has been resolved in the latest firmware commit
