### ISSUE TITLE
Lighttpd does not start Properly after new flash

### ISSUE THREAD

**Issue by jeremyroe** [CyborgUnplug/CyborgUnplug#3]
Upon flashing a TL-W710N Lighttpd does not start do to duplicate line entries in the 10-conf.d and 30-conf.d files.  Renaming one of these files allows the http server to start but content is then broken.

**Comment by JulianOliver** [comment]
Hmm, seems to work with a fresh flash here. Anyone else?

Can you give me the duplicate lines, to verify?

**Comment by nconder** [comment]
I did not have an issue on the latest release.

**Comment by JulianOliver** [comment]
OK, good to know. I don't know why you have a broken lighttpd set up there. I'd try a reinstall, perhaps using sysupgrade. 

Copy the file onto the existing system:

scp -P 3030 /path/to/firmware.bin root@10.10.10.1:.

and then:

ssh -p 3030 root@10.10.10.1

and:

sysupgrade -v firmware.bin
