### ISSUE TITLE
Migrate to using vector based images

### ISSUE THREAD

**Issue by bnvk** [CyborgUnplug/CyborgUnplug#8]
As the unPlug is often accessed over a mobile device (as well as varying resolution laptops), the images and icons crispness and rendering would be improved if it was switched to SVG or icon fonts!

EDIT: i'm happy to tackle this if it sounds like a good idea to you :wink:

**Comment by JulianOliver** [comment]
Great if you could tackle this! The newest firmware has a slightly different logo - simply the gap removed between "un" and "plug" (small change that makes a big difference to our French-speaking supporters...ouch)

**Comment by jancborchardt** [comment]
This seems fixed as now an icon font is used. :)

**Comment by bnvk** [comment]
@jancborchardt you are correct. Thanks for reminder ;)
